### ISSUE TITLE
[Suggestion] Texture Pack Compatibility

### ISSUE THREAD

**Issue by Eowomir7** [XxRexRaptorxX/OreCore#1]
This mod is amazing. Until you put a texture pack on.
then it's all vanilla textured ores on top of texture pack stone types.
please add texture pack compatibility for your mod. I'm sure more
people will use it if this happens. I will of course use it anyway.
We are going to put our own textures on there but if you can add compatibility
it would save us a lot of time on re texturing items in your mod.
It is mainly the ores because we still have to re texture all the armors and tools,
but the ores are so tedious to do, along with the fossil stands and fossils

**Comment by XxRexRaptorxX** [comment]
Sorry, but i have currently not enough time and skill to do this..

Do you make a texture pack for my mod? :>
