### ISSUE TITLE
Can we backport the mod to 1.7.10?

### ISSUE THREAD

**Issue by Omgise** [XxRexRaptorxX/OreCore#4]

**Comment by XxRexRaptorxX** [comment]
As a separate project or can i include the files in the existing project?

**Comment by Omgise** [comment]
Include a file in an existing project

**Comment by XxRexRaptorxX** [comment]
Yes, you can do backports

**Comment by Omgise** [comment]
Thank you. Maybe I should study it first

**Comment by XxRexRaptorxX** [comment]
This was one of my first projects ever when i learned to program, so don't be scared by the 'bad' code
